### PR TITLE
Add data for extracting values from a table

### PR DESCRIPTION
**Pull request by mspelman07**
PR: https://github.com/metoppv/improver/pull/2019

**lapse_rate**
Untitled

**kgo_lapse_class**
Untitled

**wind_speed_800m**
Untitled

**lapse_class**
Untitled

**kgo_gust_ratio**
Untitled

### CODE REVIEW

**Review by bayliffe — COMMENTED** [review]
kgo_gust_ratio.nc is currently internally called lapse class, the same as kgo_lapse_class.nc. I guess this makes sense as you are using the lapse class as the row for both, however the file name confused me as I assumed it would contain something to do with gusts?

**Comment by mspelman07** [comment]
You are right that when we come to use this table in real data we would rename the diagnostic to be something like "gust_ratio". In this case I wanted to test as much of the CLI functionality as I could with the acceptance tests so I left the gust ratio test without the new_name option enabled to show that if there's no new_name provided then the metadata is copied from the row cube.

**Review by MoseleyS — CHANGES_REQUESTED** [review]
When checking these new KGO files, I get the following errors from the `MOMetadataInterpreter`. Please deal with this by removing the offending keys from the input test data files so that they are not passed through (as if the inputs have been through `standardise` and had these stripped out).

I'm aware that this particular method targets a workflow where these attributes will be on the output, but that's ok as it is a non-IMPROVER workflow.

```
ValueError: Attributes KeysView(CubeAttrsDict(globals={'institution': 'Met Office', 'mosg__forecast_run_duration': 'PT12H', 'mosg__grid_domain': 'uk_extended', 'mosg__grid_type': 'standard', 'mosg__grid_version': '1.7.0', 'mosg__model_configuration': 'uk_det', 'source': 'Met Office Unified Model', 'title': 'UKV Model Forecast on UK 2 km Standard Grid', 'um_version': '11.9', 'Conventions': 'CF-1.7'}, locals={})) include one or more forbidden values ['mosg__forecast_run_duration', 'mosg__grid_domain', 'mosg__grid_type', 'mosg__grid_version', 'um_version']
```

**Comment by mspelman07** [comment]
I've removed the offending attributes and the MOMetadataInterpreter seems to be happy now.

**Review by bayliffe — APPROVED** [review]

**Review by MoseleyS — APPROVED** [review]

**Pull request merged**
