### PR TITLE
Acceptance test data needed for the height of maximum vertical veloci…

### PR DESCRIPTION
**Pull request by Katie-Howard**
…ty plugin.

### CODE REVIEW

**Review by mspelman07 — DISMISSED** [review]
The kgo is very pretty and colourful 🌈 . 

I think the only issue with this is the size of the files. In general we try to reduce the size of the repo by having files be less than 50kb where ever possible. The simplest way to do this is to take coarsen the data by slicing the cube and only taking every 30 grid points (i.e. height_of_max[0:-1:30,0:-1:30]). I'd also suggest reducing the number of height levels on the vertical_velocity_on_height_levels cube but you will then need to regenerate the kgo.

**Comment by mspelman07** [comment]
**max_vertical_velocity.nc**

Untitled

**vertical_velocity_on_height_levels.nc**

Untitled

**kgo.nc**

Untitled

**Comment by mspelman07** [comment]
New PR: https://github.com/metoppv/improver/pull/2020 
(New PR made as I can't push to the current PR's branch)

**Review by MoseleyS — APPROVED** [review]
These look fine

**Review by MoseleyS — APPROVED** [review]

**Review by mspelman07 — APPROVED** [review]

**Pull request merged**
