### PR TITLE
MOBT-661: Required changes for precipitation phase accumulations

### PR DESCRIPTION
**Pull request by brhooper**
Acceptance test data for https://github.com/metoppv/improver/pull/1997

New data for the following acceptance tests:

- test of new realization tie-breaking feature in `generate_realizations`
- test of new `manipulate_realization_dimension` CLI
- test of new functionality to apply a recursive filter to a cube containing different masks on different spatial slices.

### CODE REVIEW

**Comment by gavinevans** [comment]
Thanks @brhooper 👍 

I've added some plots of the acceptance test data updates below for reference, and added a few comments related to this data to https://github.com/metoppv/improver/pull/1997. 

tie_break_with_realization
manipulate_realization_dimension
recursive_filter_variable_mask

**Comment by brhooper** [comment]
### Updated plots of KGOs for `generate-realizations/percentiles_reordering` tests

KGO using realization tie-breaking
image

KGO using random tie-breaking
image

**Comment by gavinevans** [comment]
Would it be possible to add plots of the raw_precip_forecast.nc and multiple_percentiles_precip_cube.nc inputs to the PR?

**Comment by brhooper** [comment]
> Would it be possible to add plots of the raw_precip_forecast.nc and multiple_percentiles_precip_cube.nc inputs to the PR?

Yes, I've added them to my previous comment.

**Review by gavinevans — DISMISSED** [review]

**Review by bayliffe — COMMENTED** [review]
Some of the files in this commit are quite chunky, above our target maximum file size. That doesn't mean they cannot be used, but if you can shrink things below 100KB without destroying the usefulness of the tests, you should do so.

**Comment by brhooper** [comment]
### Second update to plots of input data and KGOs for `generate-realizations/percentiles_reordering` tests
Reduced domain size of the forecasts in the tests in order to reduce overall data volumes

Raw precipitation accumulation forecast
image

Multiple precipitation accumulation percentiles cube
image

KGO using realization tie-breaking
image

KGO using random tie-breaking
image

**Comment by brhooper** [comment]
Following review, I've made the following changes:
- removed the now obsolete acceptance test data in `data/manipulate-n-realizations` following the removal of this test (see here)
- reduced the size of the domain used in generate-realizations/percentiles_reordering tests to reduce file sizes
- deleted `data/generate-realizations/percentiles_reordering/multiple_percentiles_wind_cube.nc`, which was actually already unnecessary but I didn't notice because this file also exists in `data/generate-realizations/percentiles_rebadging`
- reduced the file size of `data/recursive-filter/input_variable_masked.nc` by saving it with compression.

**Review by bayliffe — APPROVED** [review]
Thanks for the changes.

**Review by Kat-90 — APPROVED** [review]

**Pull request merged**
